<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Symfony\\Component\\Process\\' => $vendorDir . '/symfony/process/',
    'Symfony\\Component\\EventDispatcher\\' => $vendorDir . '/symfony/event-dispatcher/',
    'GitWrapper' => $vendorDir . '/cpliakas/git-wrapper/src/',
    'GitSync' => $vendorDir . '/cpliakas/git-sync/src/',
);
